// mydr PWA - app.js
var SP="mydr_patients",SC="mydr_current",cp="",cd=null;
function ls(){try{var p=JSON.parse(localStorage.getItem(SP)||"{}"),c=localStorage.getItem(SC)||"",ks=Object.keys(p);return{patients:p,current:c||(ks.length?ks[0]:"")}}catch(e){return{patients:{},current:""}}}
function sv(p){localStorage.setItem(SP,JSON.stringify(p))}
function gp(n){var s=ls();return s.patients[n]||null}
function ej(t){var m=t.match(/```(?:json)?\s*([\s\S]*?)```/);var s=m?m[1].trim():t.trim();try{return JSON.parse(s)}catch(e){}var b=s.match(/\{[\s\S]*\}/);if(b)try{return JSON.parse(b[0])}catch(e){};return null}
function ha(o){return o&&typeof o==="object"&&Object.values(o).some(function(v){return Array.isArray(v)&&v.length>0})}
function ia(i){if(!i.referenceRange||!i.value)return false;var v=parseFloat(i.value);if(isNaN(v))return false;var r=i.referenceRange.trim();var rm=r.match(/^([\d.]+)\s*-\s*([\d.]+)$/);if(rm)return v<parseFloat(rm[1])||v>parseFloat(rm[2]);var gt=r.match(/^>=?\s*([\d.]+)/)||r.match(/^\u2265\s*([\d.]+)/);if(gt)return v<parseFloat(gt[1]);var lt=r.match(/^<=?\s*([\d.]+)/)||r.match(/^\u2264\s*([\d.]+)/);if(lt)return v>parseFloat(lt[1]);return false}
function rc(){var s=ls(),al=Object.keys(s.patients),ac=s.current||al[0]||"";if(ac)cp=ac;var h="";for(var i=0;i<al.length;i++){h+='<span class="ch'+(al[i]===cp?' ac':'"')+' dn="'+al[i]+'">'+al[i]+'</span>'}h+='<span class="ch ad" id="ba">+ 添加</span>';document.getElementById("cb").innerHTML=h;var cs=document.querySelectorAll("#cb .ch:not(#ba)");for(var j=0;j<cs.length;j++){(function(n){cs[j].onclick=function(){sw(n)}})(cs[j].getAttribute("dn"))}document.getElementById("ba").onclick=function(){om("mn")}}
function sw(n){cp=n;localStorage.setItem(SC,n);rc();rd()}
function rd(){var d=gp(cp);cd=d;var mc=document.getElementById("main");if(!d||(!d.diagnoses||!d.diagnoses.length)&&(!d.indicators||!d.indicators.length)&&(!d.medications||!d.medications.length)&&(!d.reminders||!d.reminders.length)){mc.innerHTML='<div class="em"><div class="ei">\U0001f3e5</div><h2>\u6682\u65e0\u6570\u636e</h2><p>\u70b9\u201c\U0001f4cb \u7c98\u8d34\u201d\u7c98\u8d34 DeepSeek \u56de\u590d</p></div>';return}
var dx=d.diagnoses||[],ii=d.indicators||[],mm=d.medications||[],rr=d.reminders||[],an=ii.filter(ia),dt=new Date();dt.setHours(0,0,0,0);var od=[],up=[];for(var ri=0;ri<rr.length;ri++){var r=rr[ri];if(r.nextDate){var nd=new Date(r.nextDate);if(nd<dt)od.push(r);else if(nd.getTime()-dt.getTime()<=7*24*60*60*1000)up.push(r)}}
var h='<div class="st"><div class="sc s1"><div class="n">'+dx.length+'</div><div class="l">\u8bca\u65ad</div></div><div class="sc s2"><div class="n">'+ii.length+'</div><div class="l">\u6307\u6807</div></div><div class="sc s3"><div class="n">'+an.length+'</div><div class="l">\u5f02\u5e38</div></div><div class="sc s4"><div class="n">'+mm.length+'</div><div class="l">\u7528\u836f</div></div></div>'
h+='<div class="se"><div class="stt">\u23f0 \u590d\u67e5\u63d0\u9192</div>';if(rr.length){for(var ri=0;ri<rr.length;ri++){var r=rr[ri];var c="dg",l="\U0001f7e2 \u5df2\u8ba1\u5212";for(var oi=0;oi<od.length;oi++){if(od[oi]===r){c="dr";l="\U0001f534 \u5df2\u8d85\u671f";break}}if(c!="dr"){for(var ui=0;ui<up.length;ui++){if(up[ui]===r){c="dy";l="\U0001f7e1 "+Math.ceil((new Date(r.nextDate).getTime()-dt.getTime())/86400000)+"\u5929\u540e";break}}}h+='<div class="ri"><span class="due '+c+'">'+l+'</span><span>'+r.item+'</span></div>'}}else{h+='<p class="ft">\u6682\u65e0</p>'}h+='</div>'
h+='<div class="se"><div class="stt">\U0001f48a \u7528\u836f\u8bb0\u5f55</div>';if(mm.length){var g={};for(var mi=0;mi<mm.length;mi++){var mt=mm[mi].time||"";if(!mt)continue;if(!g[mt])g[mt]=[];g[mt].push(mm[mi])}var ts=Object.keys(g).sort(function(a,b){return a==="\u6309\u9700"||!/^\d/.test(a)?1:b==="\u6309\u9700"||!/^\d/.test(b)?-1:a.localeCompare(b)});var sep={"06:30":"\U0001f305 \u65e9\u9910\u524d","07:00":"\U0001f305 \u65e9\u9910\u524d","07:30":"\U0001f305 \u65e9\u9910\u540e","12:30":"\u2600\ufe0f \u5348\u9910","18:30":"\U0001f706 \u665a\u9910\u540e","22:30":"\U0001f319 \u7761\u524d"},ll="";for(var ti=0;ti<ts.length;ti++){var l=sep[ts[ti]]||"";if(l&&l!==ll){h+='<div class="ts">'+l+"</div>";ll=l}var its=g[ts[ti]];h+='<div class="tr"><div class="tt">'+ts[ti]+'</div><div>';for(var ni=0;ni<its.length;ni++){h+=its[ni].name+(its[ni].dosage?" "+its[ni].dosage:"");if(ni<its.length-1)h+=" \u00b7 "}var nt=null;for(var nti=0;nti<its.length;nti++){if(its[nti].note){nt=its[nti].note;break}}if(nt)h+='<span style="font-size:12px;color:#94a3b8"> '+nt+"</span>";h+="</div></div>"}}else{h+='<p class="ft">\u6682\u65e0</p>'}h+='</div>'
h+='<div class="se"><div class="stt">\U0001f4cb \u75be\u75c5\u8bca\u65ad</div>';if(dx.length){var g2={};for(var di=0;di<dx.length;di++){var sys=dx[di].system||"\u5176\u4ed6";if(!g2[sys])g2[sys]=[];g2[sys].push(dx[di])}var sn=Object.keys(g2).sort(),sm={"\u7528\u836f\u4e2d":"dm","\u968f\u8bbf\u4e2d":"df","\u7a33\u5b9a":"dst"};for(var si=0;si<sn.length;si++){var its=g2[sn[si]];h+='<div class="dh" onclick=\'var e=document.getElementById("dxg'+si+'");if(e)e.classList.toggle("h")\'>'+sn[si]+'<span class="c">'+its.length+' \u9879</span></div><div class="di" id="dxg'+si+'">';for(var di2=0;di2<its.length;di2++){var st=its[di2].status||its[di2].severity||"",cl=sm[st]||"df";h+='<div class="dx"><span>'+its[di2].name+'</span><span class="ds '+cl+'">'+st+"</span></div>"}h+="</div>"}}else{h+='<p class="ft">\u6682\u65e0</p>'}h+='</div>'
h+='<div class="se"><div class="stt">\U0001f4ca \u68c0\u67e5\u6307\u6807</div>';if(ii.length){ii.sort(function(a,b){var aA=ia(a),bA=ia(b);return aA&&!bA?-1:!aA&&bA?1:(a.name||"").localeCompare(b.name||"")});for(var i2=0;i2<ii.length;i2++){var i=ii[i2];var a="\u6b63\u5e38",cl="in";if(ia(i)){var v=parseFloat(i.value),rr=(i.referenceRange||"").trim(),rm=rr.match(/^([\d.]+)\s*-\s*([\d.]+)$/);a=rm&&v<parseFloat(rm[1])?"\u504f\u4f4e":"\u504f\u9ad8";cl=a.indexOf("\u504f\u4f4e")>=0?"il":"ih"}h+='<div class="ii"><span class="in">'+i.name+'</span><span class="iv">'+(i.value||"")+'</span><span class="iu">'+(i.unit||"")+'</span><span class="ia '+cl+'">'+a+"</span></div>"}}else{h+='<p class="ft">\u6682\u65e0</p>'}h+='</div>'
h+='<p class="ft">\u6570\u636e\u66f4\u65b0: '+(d.updatedAt?new Date(d.updatedAt).toLocaleDateString("zh-CN"):"\u2014")+"</p>";mc.innerHTML=h}
function pt(t){var j=ej(t);if(j&&ha(j))return{diagnoses:j.diagnoses||[],indicators:j.indicators||[],medications:j.medications||[],reminders:j.reminders||[],timeline:j.timeline||[]};return null}
function hp(){var t=document.getElementById("it").value.trim();if(!t)return st("\u8bf7\u5148\u7c98\u8d34");var r=pt(t);if(!r||!ha(r))return st("\u65e0\u6cd5\u89e3\u6790");if(!cp)return st("\u8bf7\u5148\u6dfb\u52a0\u60a3\u8005");var ex=gp(cp)||{},mg={};for(var k in ex)mg[k]=ex[k];for(var k in r)mg[k]=r[k];mg.updatedAt=new Date().toISOString();var s=ls();s.patients[cp]=mg;sv(s.patients);cm("mi");document.getElementById("it").value="";rc();rd();st("\u2705 \u5df2\u66f4\u65b0")}
function st(m){var t=document.getElementById("tt");t.textContent=m;t.classList.add("sh");setTimeout(function(){t.classList.remove("sh")},2500)}
function om(i){document.getElementById(i).classList.add("sh")}
function cm(i){document.getElementById(i).classList.remove("sh")}
function eh(){if(!cp)return st("\u8bf7\u5148\u6dfb\u52a0\u60a3\u8005");var d=gp(cp);if(!d)return st("\u6682\u65e0\u6570\u636e");var j=JSON.stringify(d,null,2),h="<!DOCTYPE html><html><head><meta charset=UTF-8><title>"+cp+'\u00b7\u5065\u5eb7\u6863\u6848</title><style>body{font-family:sans-serif;max-width:800px;margin:0 auto;padding:20px}h1{color:#3b82f6}pre{background:#f5f6f8;border:1px solid #e2e8f0;border-radius:8px;padding:16px;overflow-x:auto}</style></head><body><h1>'+cp+'\u00b7\u5065\u5eb7\u6863\u6848</h1><p>\u5bfc\u51fa\u65f6\u95f4 '+new Date().toLocaleString("zh-CN")+'</p><pre>'+j+"</pre></body></html>";var b=new Blob([h],{type:"text/html"}),u=URL.createObjectURL(b);var a=document.createElement("a");a.href=u;a.download=cp+"-\u5065\u5eb7\u6863\u6848.html";a.click();URL.revokeObjectURL(u);st("\u2705 \u5df2\u5bfc\u51fa")}
function co(){var t={diagnoses:[{system:"\u7c7b\u522b",name:"\u75be\u75c5\u540d\u79f0",severity:"\u4e25\u91cd\u7a0b\u5ea6",status:"\u72b6\u6001",date:"\u65e5\u671f"}],indicators:[{name:"\u6307\u6807",value:"\u6570\u503c",unit:"\u5355\u4f4d",referenceRange:"\u53c2\u8003\u8303\u56f4",assessment:"\u8bc4\u4f30",date:"\u65e5\u671f"}],medications:[{time:"\u65f6\u95f4",name:"\u836f\u7269",dosage:"\u5242\u91cf",note:"\u5907\u6ce8"}],reminders:[{item:"\u9879\u76ee",lastDate:"\u4e0a\u6b21\u65e5\u671f",frequency:"\u9891\u7387",nextDate:"\u4e0b\u6b21\u65e5\u671f",status:"\u72b6\u6001"}],timeline:[{time:"\u65f6\u95f4",name:"\u4e8b\u9879",note:"\u5907\u6ce8"}]};var p="\u8bf7\u4ee5 JSON \u683c\u5f0f\u8f93\u51fa\u6211\u7684\u5168\u90e8\u5065\u5eb7\u6570\u636e\n\n"+JSON.stringify(t,null,2)+"\n\n\u53ea\u8f93\u51fa JSON\uff0c\u4e0d\u8981\u5176\u4ed6\u5185\u5bb9";if(navigator.clipboard){navigator.clipboard.writeText(p).then(function(){st("\u2705 \u5df2\u590d\u5236")})["catch"](function(){fb(p)})}else{fb(p)}}
function fb(t){var a=document.createElement("textarea");a.value=t;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();document.execCommand("copy");document.body.removeChild(a);st("\u2705 \u5df2\u590d\u5236")}
try{rc();rd();document.getElementById("bi").onclick=function(){om("mi")};document.getElementById("be").onclick=eh;document.getElementById("bc").onclick=co;document.getElementById("bp").onclick=hp;document.getElementById("mic").onclick=function(){cm("mi")};document.getElementById("mi").onclick=function(e){if(e.target===e.currentTarget)cm("mi")};document.getElementById("mnc").onclick=function(){cm("mn")};document.getElementById("bnc").onclick=function(){cm("mn")};document.getElementById("bnf").onclick=function(){var n=document.getElementById("in").value.trim();if(!n)return st("\u8bf7\u8f93\u5165\u59d3\u540d");var s=ls();if(!s.patients[n])s.patients[n]={updatedAt:new Date().toISOString()};sv(s.patients);cm("mn");sw(n)};document.getElementById("in").onkeydown=function(e){if(e.key==="Enter")document.getElementById("bnf").click()};if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")["catch"](function(){})}catch(e){console.error(e)}
